em-fe/login

README.md
emlogin/.vuepress/config.js
emlogin/README.md
emlogin/login-wap/zh-cn.md
emlogin/login/zh-cn.md

chore($easymock): api moch and modify doc

---

emlogin/login-wap/Login.vue
emlogin/login-wap/style/login.scss
emlogin/login/Login.vue
emlogin/login/style/login.scss

 fix($login): fix wap style and js

---

package.json

chore($package): config prepublishOnly

---

build/webpack.water.dev.conf.js
build/webpack.water.prod.conf.js
package.json

chore($package): dependency issues

---

emlogin/login-wap/Login.vue
emlogin/login-wap/zh-cn.md
emlogin/login/Login.vue
emlogin/login/zh-cn.md
emlogin/tools/logined.js

fix($cookie): login set cookie

---

emlogin/login-wap/Login.vue

fix($name): wap login

---

emlogin/login-wap/Login.vue
emlogin/login/Login.vue
emlogin/tools/logined.js

fix($type): add Number type

---

package.json

chore($npm): modify devDependencies

---

README.md

docs($readme): add badge

---

emlogin/tools/ajax.js

chore($cookie): delete cookie and use localStorage

---

emlogin/contant.js
emlogin/tools/logined.js

perf(contant): config contant

---

package.json

chore($npm): config lint-staged

---

package.json

build($vue): modify vue version

---

emlogin/login-wap/Login.vue
emlogin/login-wap/style/login.scss

style($modify): do better

---

emlogin/contant.js
emlogin/tools/logined.js

fix($discount): feature discount

---

emlogin/login-wap/Login.vue
emlogin/login-wap/zh-cn.md
emlogin/login/Login.vue
emlogin/tools/ajax.js

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

 fix($emlogin): fix withCredentials bug

---

emlogin/login-wap/style/login.scss

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

 style($emlogin): fix style bug

---

emlogin/login-wap/Login.vue

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

fix($emlogin): fix scroll top bug

---

emlogin/.vuepress/config.js
emlogin/emlogin.scss
emlogin/login-wechat/Login.vue
emlogin/login-wechat/__snapshots__/login.test.js.snap
emlogin/login-wechat/index.js
emlogin/login-wechat/login.test.js
emlogin/login-wechat/style/login.scss
emlogin/login-wechat/style/mixin.scss
emlogin/login-wechat/zh-cn.md
emlogin/login.js
emlogin/tools/loginedwechat.js

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

feat($emlogin): feat new wechar login

---

emlogin/login-wechat/style/login.scss

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

style($login): fix style

---

emlogin/login-wechat/style/login.scss

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

style($emlogin): pref style

---

emfelogin/checkout/checkout.scss
emfelogin/checkout/checkout.vue
emfelogin/login-wechat/Login.vue
emfelogin/login-wechat/style/login.scss
emfelogin/tools/lodash.js
package.json

首先，感谢您的贡献！:-)
额外的清单：
* []不能影响现有功能。
* []不能影响现有功能。

fix($emfelogin): feat login xuzhi
